# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bi_8g92Xu7Mhlw-WTK3ZRX6UMD6A-ENe
"""

"""
Matrix Multiplication Code
Part II - Question 1 (15 points)

This code implements matrix multiplication in two ways:
1. Manual implementation using nested loops
2. Using NumPy library for verification
"""

import numpy as np


def matrix_multiply_manual(A, B):
    """
    Multiply two matrices A and B manually using nested loops.

    Matrix multiplication rule: C[i,j] = sum of (A[i,k] * B[k,j]) for all k

    Parameters:
    -----------
    A : list of lists or numpy array
        First matrix of shape (m, n)
    B : list of lists or numpy array
        Second matrix of shape (n, p)

    Returns:
    --------
    C : list of lists
        Result matrix of shape (m, p) where C = A × B

    Raises:
    -------
    ValueError: If matrices cannot be multiplied (incompatible dimensions)
    """

    # Convert to list of lists if numpy arrays (for pure Python implementation)
    if isinstance(A, np.ndarray):
        A = A.tolist()
    if isinstance(B, np.ndarray):
        B = B.tolist()

    # Get dimensions
    m = len(A)           # Number of rows in A
    n = len(A[0])        # Number of columns in A (= rows in B)

    # Check if B has compatible dimensions
    if len(B) != n:
        raise ValueError(f"Cannot multiply: A is {m}×{n}, B is {len(B)}×{len(B[0])}")

    p = len(B[0])        # Number of columns in B

    # Initialize result matrix C with zeros
    C = [[0 for _ in range(p)] for _ in range(m)]

    # Perform matrix multiplication
    # For each row i in matrix A
    for i in range(m):
        # For each column j in matrix B
        for j in range(p):
            # Calculate C[i][j] as dot product of row i of A and column j of B
            for k in range(n):
                C[i][j] += A[i][k] * B[k][j]

    return C


def matrix_multiply_numpy(A, B):
    """
    Multiply two matrices using NumPy (efficient implementation).

    Parameters:
    -----------
    A : numpy array
        First matrix of shape (m, n)
    B : numpy array
        Second matrix of shape (n, p)

    Returns:
    --------
    C : numpy array
        Result matrix of shape (m, p) where C = A × B
    """

    # Ensure inputs are numpy arrays
    A = np.array(A)
    B = np.array(B)

    # Check dimensions
    if A.shape[1] != B.shape[0]:
        raise ValueError(f"Cannot multiply: A is {A.shape}, B is {B.shape}")

    # Use NumPy's matrix multiplication
    C = A @ B  # or np.matmul(A, B) or np.dot(A, B)

    return C


# ============================================================================
# TEST CASES
# ============================================================================

print("="*70)
print("MATRIX MULTIPLICATION - TEST CASES")
print("="*70)

# Test Case 1: Basic 2×3 and 3×2 multiplication
print("\nTest Case 1: Basic Multiplication")
print("-"*70)

A1 = [[1, 2, 3],
      [4, 5, 6]]

B1 = [[7, 8],
      [9, 10],
      [11, 12]]

print(f"Matrix A (2×3):")
for row in A1:
    print(f"  {row}")

print(f"\nMatrix B (3×2):")
for row in B1:
    print(f"  {row}")

# Manual implementation
result_manual = matrix_multiply_manual(A1, B1)
print(f"\nResult using manual implementation:")
for row in result_manual:
    print(f"  {row}")

# NumPy implementation
result_numpy = matrix_multiply_numpy(A1, B1)
print(f"\nResult using NumPy:")
print(result_numpy)

# Verify they match
print(f"\nResults match: {np.allclose(result_manual, result_numpy)}")


# Test Case 2: Square matrices (3×3)
print("\n" + "="*70)
print("Test Case 2: Square Matrices (3×3)")
print("-"*70)

A2 = [[1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]]

B2 = [[9, 8, 7],
      [6, 5, 4],
      [3, 2, 1]]

print(f"Matrix A (3×3):")
for row in A2:
    print(f"  {row}")

print(f"\nMatrix B (3×3):")
for row in B2:
    print(f"  {row}")

result_manual = matrix_multiply_manual(A2, B2)
print(f"\nResult (manual):")
for row in result_manual:
    print(f"  {row}")

result_numpy = matrix_multiply_numpy(A2, B2)
print(f"\nResult (NumPy):")
print(result_numpy)


# Test Case 3: Identity matrix multiplication
print("\n" + "="*70)
print("Test Case 3: Identity Matrix (A × I = A)")
print("-"*70)

A3 = [[2, 3],
      [4, 5]]

I = [[1, 0],
     [0, 1]]

print(f"Matrix A:")
for row in A3:
    print(f"  {row}")

print(f"\nIdentity Matrix I:")
for row in I:
    print(f"  {row}")

result_manual = matrix_multiply_manual(A3, I)
print(f"\nA × I (should equal A):")
for row in result_manual:
    print(f"  {row}")


# Test Case 4: Matrix-vector multiplication
print("\n" + "="*70)
print("Test Case 4: Matrix-Vector Multiplication")
print("-"*70)

A4 = [[1, 2, 3],
      [4, 5, 6]]

v = [[7],
     [8],
     [9]]

print(f"Matrix A (2×3):")
for row in A4:
    print(f"  {row}")

print(f"\nVector v (3×1):")
for row in v:
    print(f"  {row}")

result_manual = matrix_multiply_manual(A4, v)
print(f"\nResult A × v (2×1):")
for row in result_manual:
    print(f"  {row}")


# Test Case 5: Error handling - incompatible dimensions
print("\n" + "="*70)
print("Test Case 5: Error Handling (Incompatible Dimensions)")
print("-"*70)

A5 = [[1, 2],
      [3, 4]]

B5 = [[5, 6, 7],
      [8, 9, 10],
      [11, 12, 13]]

print(f"Matrix A: 2×2")
print(f"Matrix B: 3×3")
print(f"Attempting to multiply A × B...")

try:
    result = matrix_multiply_manual(A5, B5)
except ValueError as e:
    print(f"Error caught (as expected): {e}")


# ============================================================================
# EXPLANATION OF ALGORITHM
# ============================================================================

print("\n" + "="*70)
print("ALGORITHM EXPLANATION")
print("="*70)

print("""
Matrix Multiplication Algorithm (A × B = C):

For matrices A(m×n) and B(n×p), the result C(m×p) is calculated as:

    C[i][j] = Σ(A[i][k] × B[k][j])  for k = 0 to n-1

In words: Each element C[i][j] is the dot product of:
  - Row i from matrix A
  - Column j from matrix B

Example: If A = [1 2] and B = [5 6]
              [3 4]       [7 8]

Then C[0][0] = A[0][0]×B[0][0] + A[0][1]×B[1][0]
             = 1×5 + 2×7 = 5 + 14 = 19

Time Complexity: O(m × n × p) - three nested loops
Space Complexity: O(m × p) - for result matrix

Key Requirements:
  - Number of columns in A must equal number of rows in B
  - A(m×n) × B(n×p) = C(m×p)
  - Matrix multiplication is NOT commutative: A×B ≠ B×A
""")

print("="*70)
print("END OF MATRIX MULTIPLICATION CODE")
print("="*70)